spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emojimonitorsysdb?severTimezone=GMT%2b8
    username: root
    password: Cmy,64940310.
mybatis:
  mapper-locations: classpath:mapper/*.xml